[project]
authors = ["Marie Sacksick <marie@probabl.ai>"]
channels = ["conda-forge"]
name = "midwest_survey_models"
platforms = ["linux-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]
convert-to-notebooks = { cmd = "jupytext --to notebook ./python_files/*.py && mv ./python_files/*.ipynb ./notebooks" }
convert-to-python-files = { cmd = "jupytext --to py ./notebooks/*.ipynb && mv ./notebooks/*.py ./python_files" }

[dependencies]
python = ">=3.11.0"
jupytext = ">=1.19.1,<2"
scikit-learn = ">=1.8.0,<2"
skrub = ">=0.7.2,<0.8"
ipykernel = ">=7.2.0,<8"

[pypi-dependencies]
midwest-survey-models = { path = ".", editable = true }
